# Generated by Django 6.0 on 2025-12-10 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('auditores', '0001_initial'),
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInspecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dias_laborales_req', models.IntegerField(default=180, verbose_name='Número de días laborables requeridos')),
                ('inspecciones_minimas', models.IntegerField(default=29, verbose_name='Inspecciones mínimas')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualización')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación')),
            ],
            options={
                'verbose_name': 'Configuración de Inspecciones',
                'verbose_name_plural': 'Configuraciones de Inspecciones',
            },
        ),
        migrations.CreateModel(
            name='PeriodoValidacionCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.IntegerField(verbose_name='Número de periodo')),
                ('fecha_inicio_periodo', models.DateField(verbose_name='Fecha inicio periodo')),
                ('fecha_fin_periodo', models.DateField(verbose_name='Fecha fin periodo')),
                ('numero_dias_laborales_req', models.IntegerField(default=180, verbose_name='Número de días laborables requeridos')),
                ('inspecciones_requeridas', models.IntegerField(default=29, verbose_name='Inspecciones requeridas')),
                ('inspecciones_realizadas', models.IntegerField(default=0, verbose_name='Inspecciones realizadas')),
                ('esta_completado', models.BooleanField(default=False, verbose_name='Está completado')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha completado')),
                ('esta_vigente', models.BooleanField(default=True, verbose_name='Está vigente')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('operario_certificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodos', to='asignaciones.operariocertificacion', verbose_name='Asignación Operario-Certificación')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='periodos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualización')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='periodos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación')),
            ],
            options={
                'verbose_name': 'Periodo de Validación',
                'verbose_name_plural': 'Periodos de Validación',
                'ordering': ['operario_certificacion', 'numero_periodo'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateField(verbose_name='Fecha de inspección')),
                ('piezas_auditadas', models.IntegerField(verbose_name='Piezas auditadas')),
                ('resultado_inspeccion', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK')], max_length=10, null=True, verbose_name='Resultado inspección')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones', to='auditores.auditor', verbose_name='Auditor')),
                ('auditoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones', to='auditorias.auditoriaproducto', verbose_name='Auditoría de producto')),
                ('operario_certificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones', to='asignaciones.operariocertificacion', verbose_name='Asignación Operario-Certificación')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualización')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación')),
                ('periodo_validacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inspecciones', to='inspecciones.periodovalidacioncertificacion', verbose_name='Periodo de validación')),
            ],
            options={
                'verbose_name': 'Inspección de Producto',
                'verbose_name_plural': 'Inspecciones de Producto',
                'ordering': ['-fecha_inspeccion', '-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodovalidacioncertificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_vigente', True)), fields=('operario_certificacion',), name='periodo_vigente_unico'),
        ),
        migrations.AlterUniqueTogether(
            name='periodovalidacioncertificacion',
            unique_together={('operario_certificacion', 'numero_periodo')},
        ),
        migrations.AddIndex(
            model_name='inspeccionproducto',
            index=models.Index(fields=['operario_certificacion', 'fecha_inspeccion'], name='inspeccione_operari_1ad70e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccionproducto',
            index=models.Index(fields=['periodo_validacion', 'fecha_inspeccion'], name='inspeccione_periodo_2bca63_idx'),
        ),
    ]
