# Generated by Django 6.0 on 2025-12-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionproducto',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Número de orden que generó las piezas', max_length=100, null=True, verbose_name='Número de orden'),
        ),
        migrations.AlterField(
            model_name='configuracioninspecciones',
            name='inspecciones_minimas',
            field=models.IntegerField(default=29, help_text='Número total de piezas que deben ser auditadas por periodo (29 por defecto)', verbose_name='Piezas mínimas requeridas'),
        ),
        migrations.AlterField(
            model_name='periodovalidacioncertificacion',
            name='inspecciones_realizadas',
            field=models.IntegerField(default=0, help_text='Total de piezas auditadas en este periodo (suma de piezas_auditadas de todas las inspecciones)', verbose_name='Piezas realizadas'),
        ),
        migrations.AlterField(
            model_name='periodovalidacioncertificacion',
            name='inspecciones_requeridas',
            field=models.IntegerField(default=29, help_text='Número total de piezas que deben ser auditadas en este periodo (29 por defecto)', verbose_name='Piezas requeridas'),
        ),
    ]
