# Generated by Django 6.0 on 2025-12-10 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificaciones', '0001_initial'),
        ('operarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperarioCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de asignación')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está activa')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operarios', to='certificaciones.certificacion', verbose_name='Certificación')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificaciones', to='operarios.operario', verbose_name='Operario')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualización')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación')),
            ],
            options={
                'verbose_name': 'Asignación Operario-Certificación',
                'verbose_name_plural': 'Asignaciones Operario-Certificación',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('operario', 'certificacion', 'fecha_asignacion')},
            },
        ),
    ]
