# Generated by Django 6.0 on 2025-12-10 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auditorias', to='certificaciones.certificacion', verbose_name='Certificación')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auditorias_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualización')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación')),
            ],
            options={
                'verbose_name': 'Auditoría de Producto',
                'verbose_name_plural': 'Auditorías de Producto',
                'ordering': ['certificacion', 'nombre'],
                'unique_together': {('certificacion', 'nombre')},
            },
        ),
    ]
